// Automatically generated by astro-icon
// c1a452a426ab30436bccd4e6abeb406512dd30e9f73ab2519c1853de47b35dca

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "bi-hand-index-thumb"
		| "bi-mouse3"
		| "solar-banknote-2-line-duotone"
		| "solar-case-line-duotone"
		| "solar-case-minimalistic-line-duotone"
		| "solar-code-square-line-duotone"
		| "solar-cpu-line-duotone"
		| "solar-electric-refueling-line-duotone"
		| "solar-hand-stars-line-duotone"
		| "solar-money-bag-line-duotone"
		| "solar-monitor-smartphone-line-duotone"
		| "solar-stars-minimalistic-line-duotone"
		| "solar-suitcase-bold-duotone";
}